version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: zen-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - zen-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


  dagster:
    build:
      context: .
    container_name: zen-dagster
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./local/dagster/home:/opt/dagster/dagster_home
      - ./local/warehouse:/app/local/warehouse
      - .:/app
      - ./local/dbt/profile:/root/.dbt
    ports:
      - "${DAGSTER_PORT}:3000"
    depends_on:
      - postgres
    networks:
      - zen-network
    working_dir: /app
    entrypoint: ["dagster", "dev", "--host", "0.0.0.0"]
#    entrypoint: ["tail", "-f", "/dev/null"]


  metabase:
    image: metabase/metabase:latest
    container_name: zen-metabase
    volumes:
      - ./local/metabase/urandom:/dev/random:ro
      - ./local/metabase/data:/metabase-data
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    ports:
      - "${METABASE_PORT}:3000"
    networks:
      - zen-network

volumes:
  postgres_data:

networks:
  zen-network:
    driver: bridge